// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOq1EMTUDFBXadaUTQOY-X_yfLs4tCZHQ',
    appId: '1:852943530423:web:f9f10f68b3f902980fe032',
    messagingSenderId: '852943530423',
    projectId: 'acadenocrm',
    authDomain: 'acadenocrm.firebaseapp.com',
    storageBucket: 'acadenocrm.firebasestorage.app',
    measurementId: 'G-1QDXB79VJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVwPd8JbmR7YJQG0h3-35t966Lj9t_zs',
    appId: '1:852943530423:android:520925ded6f8194d0fe032',
    messagingSenderId: '852943530423',
    projectId: 'acadenocrm',
    storageBucket: 'acadenocrm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68ei2DXwH0fneCSR-o82-gAj-O6gHWVo',
    appId: '1:852943530423:ios:403886edbb746da80fe032',
    messagingSenderId: '852943530423',
    projectId: 'acadenocrm',
    storageBucket: 'acadenocrm.firebasestorage.app',
    iosBundleId: 'com.example.acadenoCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68ei2DXwH0fneCSR-o82-gAj-O6gHWVo',
    appId: '1:852943530423:ios:403886edbb746da80fe032',
    messagingSenderId: '852943530423',
    projectId: 'acadenocrm',
    storageBucket: 'acadenocrm.firebasestorage.app',
    iosBundleId: 'com.example.acadenoCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOq1EMTUDFBXadaUTQOY-X_yfLs4tCZHQ',
    appId: '1:852943530423:web:00e351c65b0d63fb0fe032',
    messagingSenderId: '852943530423',
    projectId: 'acadenocrm',
    authDomain: 'acadenocrm.firebaseapp.com',
    storageBucket: 'acadenocrm.firebasestorage.app',
    measurementId: 'G-T304F4RJ7H',
  );
}
